### ISSUE TITLE
Kindly share camera.yml and map.yml format

### ISSUE THREAD

**Issue by knazneen123** [elliotwoods/ArUco-MarkerMapper#2]
The format for yml is not mentioned anywhere in the code

**Comment by elliotwoods** [comment]
Please note that the author of this code is Rafael Muñoz-Salinas
He does not use GitHub, and this version here is only my fork of his code

you can see some of my processed data (including the files you requested) at:
https://www.dropbox.com/sh/vr5ok00l2svlvss/AAD1oPlQMEc4gfnsDs42lBPna?dl=0
